language: java

sudo: false

notifications:
  email:
    - renato.mendes.1123@gmail.com

branches:
  only:
    - 0.0.1

jdk:
  - openjdk8

before_install:
  - cp .travis.maven.settings.xml $HOME/.m2/settings.xml

install:
  - cd parent
  - mvn deploy

#deploy:
#  provider: script
#  skip_cleanup: true
#  script:
#    - cp .travis.maven.settings.xml $HOME/.m2/settings.xml
#    - mvn deploy  
#  on:
#    tags: true


